name: Test
on: [push]
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: Test
        uses: j-c-cook/python-test-action@master

